### ISSUE TITLE
Your tutorial is very helpful

### ISSUE THREAD

**Issue by Christaline-George** [ErnakovichLab/tutorials#2]
Dear @hhollandmoritz  and team,

I do not have an issue to raise but decided to use this platform for thanking you for putting this tutorial together.

It has been super helpful for me to understand how to process and analyze my Novaseq reads. 

We will be citing you in our upcoming paper and was wondering if there is any preferred way of citing your work using this tutorial?

**Comment by hhollandmoritz** [comment]
Hi @chrissy005 Thank you for the wonderful feedback, we really appreciate it. I've just added a citation mechanism to the repository. You should be able to download it as either a bibtex or directly into Zotero (if you use Zotero) from the repository now. On the right hand side of the page under "About" there's a "Cite this repository" drop-down menu that should get you there. Please remember to also cite the creators of DADA2 since we largely repurposed their big data tutorial and added some code to handle the NovaSeq discussions on the github issues page.
